### ISSUE TITLE
Upgrading Unity to 2019.2.12f1 Caused Java Exception <NoSuchMethodError>

### ISSUE THREAD

**Issue by soh2131** [Unity-Technologies/com.unity.mobile.notifications#1]
Everything was working until we upgraded Unity to 2019.2.12f1 yesterday.

We use our own activity wrapper

Have encountered this problem with Android version 7-10

Using package version 1.0.3

100% reproducible

Here's the error:

> 
> 11-19 11:45:27.774 30130 30198 E Unity   : LuaExceptionWithStackTrace: c# exception:UnityEngine.AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='findResourceidInContextByName' signature='(Ljava/lang/String;Landroid.app.Application;Lcom.wildsky.plugin.UnityActivityWrapper;)I' in class Lcom.unity.androidnotifications.UnityNotificationManagerOreo;
> 11-19 11:45:27.774 30130 30198 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
> 11-19 11:45:27.774 30130 30198 E Unity   :   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <00000000000000000000000000000000>:0 
> 11-19 11:45:27.774 30130 30198 E Unity   :   at UnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
> 11-19 11:45:27.774 30130 30198 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
> 11-19 11:45:27.774 30130 30198 E Unity   :   at UnityE
> 11-19 11:45:39.542 30489 30556 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3656mb
> 11-19 11:45:39.542 30489 30556 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
> 11-19 11:45:39.543 30489 30556 I Unity   : ApplicationInfo com.wildsky.td version 1.6.14 build a0fcd094-d663-4b71-b165-ac247da8ea9d
> 11-19 11:45:39.543 30489 30556 I Unity   : Built from '2019.2/staging' branch, Version '2019.2.12f1 (b1a7e1fb4fa5)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
> 11-19 11:45:39.874 30489 30556 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_b
> 11-19 11:45:39.874 30489 30556 D Unity   : order_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_E
> 11-19 11:45:39.874 30489 30556 D Unity   : XT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density
> 11-19 11:45:40.230 30489 30556 I Unity   : UnityEngine.Scripting.GarbageCollector.isIncremental = True

**Comment by soh2131** [comment]
> 11-19 13:45:43.687  7442  7471 E Unity   : AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
> 11-19 13:45:43.687  7442  7471 E Unity   : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:224)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeFocusChanged(Native Method)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at com.unity3d.player.UnityPlayer.a(Unknown Source:0)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:177)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:103)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at android.os.Looper.loop(Looper.java:214)
> 11-19 13:45:43.687  7442  7471 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
> 11-19 13:45:43.687  7442  7471 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1396 
> 11-19 13:45:43.687  7442  7471 E Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntP
> 

This happens in the SampleProject as well as our projects using Pixel 2 Android 10 with Unity 2019.2.12f1

**Comment by jackatfp** [comment]
it also happens in 2019.2.11f1

**Comment by soh2131** [comment]
Here's how to fix this:

find the line in function SendNotification of AndroidNotificationCenter.cs
replace 

>                 int smallIconId = notificationManager.CallStatic<int>("findResourceidInContextByName",
>                     notification.smallIcon, androidContext, activity);

with

>                 int smallIconId = managerClass.CallStatic<int>("findResourceidInContextByName",
>                     notification.smallIcon, androidContext, activity);

Also do this for others in the same function that calls "findResourceidInContextByName"

Problem solved.

**Comment by jackatfp** [comment]
Thanks! but where can I find that class? I cannot find it in Assets folder

**Comment by jackatfp** [comment]
Thanks!

**Comment by Klipi** [comment]
Thanks for the workaround! Would it be possible to push a 1.0.4 update with this change into the Unity Package Manager? We're currently manually patching the package, but it needs to be done on each dev machine and repository separately.

**Comment by MaelHaquin** [comment]
Hi, I made a quick script who replace the file with the error with a fixed copy of the script when you build.
All you have to do is set the path of the both files in the FileUtil.ReplaceFile() function.

`#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;

class FixAndroidNotificationPackage : IPreprocessBuildWithReport
{
    [MenuItem("Tool/FixAndroidNotifications")]
    static void FixAndroidNotifications()
    {
        // CHANGE PATH HERE
        FileUtil.ReplaceFile("set path of your file", "set path of destination file");
    }

    public int callbackOrder { get { return 0; } }
    
    public void OnPreprocessBuild(BuildReport report)
    {
        FixAndroidNotifications();
    }
}
#endif`

**Comment by KaloaGames** [comment]
Thanks! solved my Problem too

**Comment by vincent-unity** [comment]
Is this still a problem? I didn't check the previous version, but it should have been fixed in the latest 1.1.0-preview.
