### ISSUE TITLE
IOS Location Notifications not working - repro'd with Xcode Sim and the test project

### ISSUE THREAD

**Issue by ROBYER1** [Unity-Technologies/com.unity.mobile.notifications#102]
Reported in Unity **Bug Report Case 1350063** after pulling the test project from github and trying to get the location triggers to work from there. It seems there is a test location notification button that just sets up a location notification at lat/long 0/0 which does absolutely nothing, when changing that to my location or London/Tokyo which can be simulated in Xcode with a reasonable radius and simulating the location in Xcode after both in and out, the notifications do not fire.

This is using Xcode > Debug > Simulate Location options when launching the app from Xcode.

As far as I can see this functionality is totally not working and we need it for a current project. Is there anyone who can look into this? I don't understand why the test project in the repo is showing it not working too, isn't the test project there so that it can be verified as working? I hope it is just me missing something small.

**Comment by lucas-zaubar** [comment]
Yes, we also tried both in simulator and on device. I'm able to allow notifications, but no notifications are triggered when on specified coordinates.

**Comment by aurimasc** [comment]
I can't get location based notifications to work on Simulator at all, but I can get them working on real device.
Couple caveats:
- if you want to "enter" the location, you need to first simulate location outside the area, followed by inside; simulating inside right away does not trigger (but follow up outside would trigger the "leave")
- pay attention that Center is x=latitude,y=longitude, rather misleading, hence changing here:
https://github.com/Unity-Technologies/com.unity.mobile.notifications/pull/218
