### ISSUE TITLE
[Bug] Unity Editor resets Notification config

### ISSUE THREAD

**Issue by Nyankoo** [Unity-Technologies/com.unity.mobile.notifications#131]
I'm setting notification settings via the editor config page (Project Settings -> Mobile Notification), but sometimes after a build, all settings are reset to the default values, like when the asset is freshly installed.

I'm still not sure when exactly this is happening, but maybe it's already a known issue?

Unity Editor: version 2020.3.22f (also happens with previous 2020 versions)
Mobile Notification: version 1.4.2

**Comment by aurimasc** [comment]
I believe this bug has been fixed in 2.0.0. Please, reopen if you can reproduce it there.
