### ISSUE TITLE
Critical error in reading userInfo from received notification on iOS produces a crash

### ISSUE THREAD

**Issue by miv** [Unity-Technologies/com.unity.mobile.notifications#132]
When iOS Notification has been received this library deserialise it's userInfo content using iOS internal NSJSONSerialization function. This all happens in [`UnityNotificationData.mm` in `_ReadNSDictionary` function. ](https://github.com/Unity-Technologies/com.unity.mobile.notifications/blob/1.4.2/com.unity.mobile.notifications/Runtime/iOS/Plugins/UnityNotificationData.m#L214)

During iterating of userInfo this function assumes that values can be only strings or json objects. This is incorrect as userInfo is created from ordinary json payload passed to APS and **lead to a crash** if values other than string or object are placed in payload.

As Apple's doc states:

> Your custom keys must have values with primitive types, such as dictionary, array, string, number, or Boolean. Custom keys are available in the userInfo dictionary of the UNNotificationContent object delivered to your app.

Currently passing any value other than string or object to userInfo payload produces a crash. Example:

`{"t":"b","i":110,"aps":{"alert":{"body":"[stage] Test"},"badge":1,"content-available":1}}`

In this example `"t":"b"` is deserialised ok but `"i":110` **produces a crash**.

As far as i can see this has not been fixed in current master.

--

Workaround for now - use only string or object values for payload to avoid a crash

**Comment by miv** [comment]
I want to add that parsing user input  without a `@try/@catch` is a very bad idea. And userInfo is basically user input (thou passed through apple services when using remote notifications).

**Comment by aurimasc** [comment]
Should be fixed by this: https://github.com/Unity-Technologies/com.unity.mobile.notifications/pull/134

**Comment by miv** [comment]
So, what will happen if Boolean is passed as one of the values?
