### ISSUE TITLE
[Android] Doesn't work with android 12

### ISSUE THREAD

**Issue by sbmgamescom** [Unity-Technologies/com.unity.mobile.notifications#133]
The package does not work with android 12. When trying to install APK, it gives an error: "There was a problem parsing the package". Also does not work when trying to download from Google play. I spent a couple of days trying to find out what the issue is. When I removed this package, everything worked. The error only appears with android SDK 31. App works with android SDK 30 but not correctly.

Unity version: 2020.3.23f1
Unity Mobile Notifications 1.4.2
Platform: Android
Platform OS version: Android 12
Any specific devices issue occurs on: Google Pixel 4(Android 12)

**Comment by aurimasc** [comment]
Fixed in master.
