### ISSUE TITLE
[Android] android.os.Transaction.TooLargeException data parcel size 16592448 bytes

### ISSUE THREAD

**Issue by CriticalForce** [Unity-Technologies/com.unity.mobile.notifications#144]
Using mobile notifications package 1.5.0 (as a custom package as 1.4.2 was unusable for us due to a crash introduced there)

Here is the stacktrace:
![image](https://user-images.githubusercontent.com/11941373/149460250-2d29cd1f-ffa7-4db8-bd8f-1ee9d7902957.png)

**Comment by aurimasc** [comment]
Can you provide a repro case for this?

**Comment by CriticalForce** [comment]
I traced it down to: 
AndroidNotificationCenter.SendNotificationWithExplicitID(notificationData, channel, (int)type);

After using the above there was no longer another debug.
Not sure which of the inputs would have caused this.

```
            var notificationData = new AndroidNotification
            {
                
                Title = title,
                Text = body,
                FireTime = time,
                IntentData = ((int)type).ToString(),
                ShouldAutoCancel = true,
                LargeIcon = "cops_push_notif_icon",
            };
```

**Comment by aurimasc** [comment]
I've tried with non existent icon - in such case no icon is displayed for me.
Maybe the icon is very large? How big is it?

**Comment by CriticalForce** [comment]
> I've tried with non existent icon - in such case no icon is displayed for me. Maybe the icon is very large? How big is it?
This is a 512x512 file it would seem, I think it must have been like that for ages for us I'll try to reduce it a bit.

**Comment by CriticalForce** [comment]
> > I've tried with non existent icon - in such case no icon is displayed for me. Maybe the icon is very large? How big is it?
> 
> This is a 512x512 file it would seem, I think it must have been like that for ages for us I'll try to reduce it a bit.

I even downsized to 384x384 and still experiencing the issue. Will try to use the minimum required size (192x192)

**Comment by aurimasc** [comment]
Could you report this bug via Unity Editor instead providing an image itself and a small project to reproduce it. Also mention what kind of devices the issue occurs on.
