### ISSUE TITLE
EndOfStreamExeception Error On IOS and Android

### ISSUE THREAD

**Issue by karadot** [Unity-Technologies/com.unity.mobile.notifications#155]
Hi, I'm using GameNotificationManager in my scripts but got some errors about file reading. I chose "Clear On Foregrounding" on GameNotificationManager component. I can't reproduce error, only one of my colleagues has got this error once. But we are get lot of logs from analytics about that. 

Unity Version: 2020.3.27f1

Mobile Notifications Version: 1.4.2

Error :
System.IO.__Error.EndOfFile () (at <00000000000000000000000000000000>:0)
System.IO.BinaryReader.ReadByte () (at <00000000000000000000000000000000>:0)
NotificationSamples.DefaultSerializer.Deserialize (NotificationSamples.IGameNotificationsPlatform platform) (at <00000000000000000000000000000000>:0)
NotificationSamples.GameNotificationsManager.OnForegrounding () (at <00000000000000000000000000000000>:0)
NotificationSamples.GameNotificationsManager.OnApplicationFocus (System.Boolean hasFocus) (at <00000000000000000000000000000000>:0)

**Comment by aurimasc** [comment]
This should improve it: https://github.com/Unity-Technologies/NotificationsSamples/pull/69
