### ISSUE TITLE
Can not publish on google play store 

### ISSUE THREAD

**Issue by vongsomxai** [Unity-Technologies/com.unity.mobile.notifications#156]
When use Notification pakage there is this error when uploaded to google play store.

You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: developer.android.com/about/versions/12/behavior-changes-12#exported"

I hope you could release this change as verified pakage soon.

**Comment by aurimasc** [comment]
This one should be fixed in 2.0.0
