### ISSUE TITLE
Can not see version 2.0.0 in Unity package manager in 2021.2.10f

### ISSUE THREAD

**Issue by lukaslabaj** [Unity-Technologies/com.unity.mobile.notifications#157]
Hi, am I missing something but I can not see latest version 2.0.0 in Unity 2021.2.10f. It is possible to install this version in Unity 2020.3.18

**Comment by aurimasc** [comment]
Notification package 2.0.0 is available in releases where it was officially verified. You can install it to older releases by manually specifying version in manifest.json:
"com.unity.mobile.notifications": "2.0.0"
