### ISSUE TITLE
Custom background image for android notification

### ISSUE THREAD

**Issue by devauk** [Unity-Technologies/com.unity.mobile.notifications#164]
Is there a way to customise notification background image (notification type big picture style) in Unity mobile notification, currently the notification comes with a white background. As I know there is a support for this in native android. Is there a provision for this in unity mobile notification

**Comment by e1iman** [comment]
this should be "supported" in https://docs.unity3d.com/Packages/com.unity.mobile.notifications@2.0/changelog/CHANGELOG.html

>[iOS] Added support for the following notification attachements: images, sounds, videos.
>[Android] Introduced AndroidNotificationCenter.CreateNotificationBuilder, which allows the greater customizability while creating notifications.

**Comment by aurimasc** [comment]
Correct, you have to use the builder directly.

**Comment by yenmoc** [comment]
![image](https://user-images.githubusercontent.com/44673303/167079161-a5e6d06a-159a-42cd-81b9-cef77a7c3931.png)
****

When I look in the source code, I see that the bigpicture is being hidden, seems like this feature is not available yet?
