### ISSUE TITLE
Mobile Notificaion v2.0.0 or above have a delay bug

### ISSUE THREAD

**Issue by azuma560** [Unity-Technologies/com.unity.mobile.notifications#184]
Setting notifications using Mobile Notifications delays notifications. The larger the elapsedTime, the larger the delay.
Specifically, if you set the notification schedule after 30 seconds, it will be delayed by about 15 seconds.

build OS: macOS 12.0.1
device: Google Pixel 6
os: Android12
Mobile Notifications: v2.0.0 or v2.0.1
Unity: 2020.3.32

**Comment by aurimasc** [comment]
Could you report this via Unity bug reporter with a project where this can be reproduced?
Cause report like this is not useful.
