### ISSUE TITLE
Provisional permission doesn't exit

### ISSUE THREAD

**Issue by IgorGalimski** [Unity-Technologies/com.unity.mobile.notifications#189]
Hi!
In 2.0.1 was added provisional permission. But it's not presented in C# side. Native side return 3 as int and it deserialised as NotDetermined value

<img width="765" alt="Screenshot 2022-05-13 at 16 25 38" src="https://user-images.githubusercontent.com/19680568/168307218-eeabf7c7-366a-4e1f-904a-40b9a50f25b7.png">

**Comment by aurimasc** [comment]
Fixed in master.
