### ISSUE TITLE
[Feature Request] Please add BigPictureStyle Notification (For Android)

### ISSUE THREAD

**Issue by wony855** [Unity-Technologies/com.unity.mobile.notifications#194]
Hello~

I tried to implement BigPictureStyle Notification using builder but failed...
I hope you officially support this feature

Thank you

**Comment by sagardaingade** [comment]
I am waiting for this feature.

**Comment by yenmoc** [comment]
i'm waiting too

**Comment by aurimasc** [comment]
Implemented in master.
