### ISSUE TITLE
[Feature Request] Notification without sound 

### ISSUE THREAD

**Issue by hanilozmen** [Unity-Technologies/com.unity.mobile.notifications#202]
I believe that it is generally best practice to send push notifications without sound for regular notifications. It is achievable in android by arranging push notification priority(low priority in general). However, it is not available in ios currently( v.2.0.2).

After a little investigation, I came up with a workaround in ios : 
In this file , _com.unity.mobile.notifications/Runtime/iOS/Plugins/UnityNotificationManager.m_ 
I commented out the line ( line 301) for this purpose:
` //content.sound = [UNNotificationSound defaultSound];`

I think that it would be nice to add a bool parameter to _Unity.Notifications.iOS.iOSNotification_ class in the library.

**Comment by aurimasc** [comment]
Feature implemented.
