### ISSUE TITLE
ANR : android.os.MessageQueue.nativePollOnceBroadcast

### ISSUE THREAD

**Issue by tomurtogu** [Unity-Technologies/com.unity.mobile.notifications#214]
There are ANRs for Android 11 (Google Play Vitals)

Unity 2020.3.33f1
Mobile Notifications v2.02
Target SDK 31

`Native method - android.os.MessageQueue.nativePollOnceBroadcast of Intent { cmp=com.xxx.xxx/com.unity.androidnotifications.UnityNotificationManager }`

**Comment by Bruno-LKWD** [comment]
Any news about this?

**Comment by tomurtogu** [comment]
@Bruno-LKWD no. it still persists.

**Comment by Bruno-LKWD** [comment]
Did you try with 2.1.0?

**Comment by aurimasc** [comment]
Please try with 2.1.0 and reopen in case the problem persists.
