### ISSUE TITLE
I still get the "NotSupportedException" error when I build my project for android

### ISSUE THREAD

**Issue by 452283662** [Unity-Technologies/com.unity.mobile.notifications#222]
The plugin version I am using is 2.0.2, Unity version 2020.3.38f1

I see "Fix unguarded API usage from level 23" in the change log.  And I see in the UnityNotificationManager.java script, that the getActiveNotifications call has been protected. Does this mean that this plugin package already supports Android API Level 23 and below. But then I get NotSupportedException error when I build my project. This makes me a bit confused. My project is set to API Level 19. I don't want to set my project to API Level 23 easily, so I'm asking here. 
Is this error a false alarm?

![image](https://user-images.githubusercontent.com/19565197/190837850-615d635d-17c0-4f26-abfa-0dd056f8b6bd.png)

**Comment by aurimasc** [comment]
For 2.0.2 version minimum required API level is 21.
If you want to target lower, use version 1.4.3.
