### ISSUE TITLE
This file can't be installed on Android 12 or higher. See:

### ISSUE THREAD

**Issue by Vah94** [Unity-Technologies/com.unity.mobile.notifications#230]
Mobile Notifications version 2.0.2
After upload build

You uploaded an APK or Android App Bundle which has an activity, activity alias, service or broadcast receiver with intent filter, but without 'android:exported' property set. This file can't be installed on Android 12 or higher. See: [developer.android.com/about/versions/12/behavior-changes-12#exported](http://developer.android.com/about/versions/12/behavior-changes-12#exported)

**Comment by aurimasc** [comment]
Are you sure this is from notifications package?
We do set exported attribute for receivers.

**Comment by aurimasc** [comment]
Closing, as no new info provided.
