### ISSUE TITLE
Set Pause app activity if unused to false on Android 13

### ISSUE THREAD

**Issue by fcourant** [Unity-Technologies/com.unity.mobile.notifications#234]
When running app on android 13 it theems that Pause app activity if unused is activated by default :

![image](https://user-images.githubusercontent.com/108724280/201085560-506c3d9b-0a2e-4220-9695-1362d9255cff.png)

**Comment by aurimasc** [comment]
I think this is the default behavior. So notification permission will be removed if app is not launched for few months.
Has nothing to do with notifications package.
