### ISSUE TITLE
Notification don't go 

### ISSUE THREAD

**Issue by IgorGalimski** [Unity-Technologies/com.unity.mobile.notifications#238]
Mobile notification package 2.1.0
Notifications that were scheduled in 1 or 5 seconds - notifications go, for 2 minutes or more - don't go
But notifications scheduled for version 2.0.2 (1 or 5 seconds, 2 minutes or more) - go every time
We didn't change scheduled scripts

Also, if notifications were scheduled on the previous version of unity package (2.0.2) and we install a build with the latest package (2.1.0) - notifications work. It means - something is broken with scheduled notification mechanism in 2.1.0

**Comment by aurimasc** [comment]
Can you provide a sample project with the issue?

**Comment by IgorGalimski** [comment]
[TestMobileNotification.zip](https://github.com/Unity-Technologies/com.unity.mobile.notifications/files/10184932/TestMobileNotification.zip)

Please, check it out
We don't get notifications on the lock screen, only in the notification center

**Comment by aurimasc** [comment]
Well, the test project requests notification authorization with Provisional flag set, so it means it will be auto granted, but notifications will work silently.

**Comment by IgorGalimski** [comment]
Yes, but in some cases we didn't get any notifications
But we always got them on 2.0.2 version

**Comment by IgorGalimski** [comment]
Related to this issue
https://github.com/Unity-Technologies/com.unity.mobile.notifications/issues/242
