### ISSUE TITLE
NRE when update mobile notifications package from 2.0.2 to 2.1.0 iOS

### ISSUE THREAD

**Issue by IgorGalimski** [Unity-Technologies/com.unity.mobile.notifications#242]
In 2.1.0 you changed the way to store UtcTime - now you have it in a dict
2.1.0
<img width="1157" alt="Screenshot 2022-12-15 at 16 09 35" src="https://user-images.githubusercontent.com/19680568/207883572-c14bcbb1-4347-41e1-ad5a-99d58c530b13.png">

But before it was just a property in iOSNotification class
2.0.2
<img width="1169" alt="Screenshot 2022-12-15 at 16 07 04" src="https://user-images.githubusercontent.com/19680568/207883590-bf0ae6d6-646c-4c0f-808d-127acc2c2bef.png">

So, when we update mobile notification package - we faced a NRE, because you don't have a check for "OriginalUtc" key. It happened when users had previous verison (2.0.2) and update to the latest one (2.1.0). Next opening won't throw the NRE because the value for the key is gonna be added:
<img width="826" alt="Screenshot 2022-12-15 at 16 20 00" src="https://user-images.githubusercontent.com/19680568/207884648-1073c341-cc66-416b-9a0f-33a6afa3a23f.png">

**Comment by aurimasc** [comment]
Will be fixed in next release.
