### ISSUE TITLE
ANR in background caused by NotificationCallback.onSentNotification invoking JavaProxy

### ISSUE THREAD

**Issue by AntonPetrov83** [Unity-Technologies/com.unity.mobile.notifications#245]
Hi!

We experience a lot of this ANRs:

![image](https://user-images.githubusercontent.com/1997978/209475850-3d4ae15c-eda0-4fc0-a7c3-a435d90d4b60.png)

Mostly happen in background when android activity gets stopped on application quit.

Unity: 2020.3.38f1
Mobile notification package: pre 2.0.2

**Comment by AntonPetrov83** [comment]
> Do your logs show that app quits at the same time as this happens?

Yes.

**Comment by aurimasc** [comment]
Then it's probably that bug. Closing on that basis.
