### ISSUE TITLE
Notification permission request can be done twice 

### ISSUE THREAD

**Issue by IgorGalimski** [Unity-Technologies/com.unity.mobile.notifications#248]
Hi
We use mobile notification package 2.1.1 and notified that the permission popup can be shown the second time if the first time if was declined. Please, checkout the video. I use google pixel 6a with the latest android 13, android target SDK is 33

Is it a bug in android?

https://user-images.githubusercontent.com/19680568/213463166-29cefce8-404b-4ea4-98cc-7bab67a828d5.mp4

**Comment by IgorGalimski** [comment]
Requesting the permission 2 times - android feature, not a bug
https://developer.android.com/training/permissions/requesting#explain
https://developer.android.com/develop/ui/views/notifications/notification-permission#wait-to-show-prompt

But actually mobile notifications plugins doesn't check for 
Would be great to have a bool property - if the first time popup was declined. Also, it will be possible to get rid of saved status. Now we detect for the permission status like this:

<img width="818" alt="Screenshot 2023-01-20 at 20 58 15" src="https://user-images.githubusercontent.com/19680568/213782945-7044a4e9-87f7-45f0-a603-205f0a7e9b78.png">

**Other issues:**
When the popup was shown for the first time
User clicked "Denied" -> callback PermissionCallbacks.PermissionDenied is invoked
User swiped away -> callback PermissionCallbacks.PermissionDeniedAndDontAskAgain

User denied the popup. The popup was shown the second time:
Users clicked "Denied" -> callback PermissionCallbacks.PermissionDeniedAndDontAskAgain
User swiped away -> callback PermissionCallbacks.PermissionDenied is invoked

So, now when we need to hook for the callbacks and have our own logic - we can't really do it, because they are messed
Is it possible to have wrappers over these engine's callbacks? To have 3 specific callbacks like:
* PermissionGranted
* PermissionDeniedFirstTime
* PermissionDeniedDon'tAskAgain
* PermissionSwipedAway

**Comment by aurimasc** [comment]
That's not exactly how it work. We'll do an update to API for it.

**Comment by aurimasc** [comment]
Added new API to check, if permission rationale should be explained.
