### ISSUE TITLE
Native method - android.os.MessageQueue.nativePollOnce Broadcast of Intent { cmp=linkdesks.pop.bubblegames.bubbleshooter/com.unity.androidnotifications.UnityNotificationManager }

### ISSUE THREAD

**Issue by mry-ship** [Unity-Technologies/com.unity.mobile.notifications#252]
#00  pc 0x00000000002fe297  /apex/com.android.runtime/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+78)
  #01  pc 0x00000000003a6bdb  /apex/com.android.runtime/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+358)
  #02  pc 0x00000000003a33b3  /apex/com.android.runtime/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
  #03  pc 0x00000000003bbc2d  /apex/com.android.runtime/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+576)
  #04  pc 0x00000000003b65dd  /apex/com.android.runtime/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+296)
  #05  pc 0x00000000003b5cfd  /apex/com.android.runtime/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+1416)
  #06  pc 0x00000000003b5691  /apex/com.android.runtime/lib/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+640)
  #07  pc 0x000000000038033b  /apex/com.android.runtime/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+130)
  #08  pc 0x000000000038ecad  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::HandleSigQuit()+1036)
  #09  pc 0x000000000038e117  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::Run(void*)+242)
  #10  pc 0x00000000000a6293  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  #11  pc 0x0000000000060803  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)

  #00  pc 0x000000000005a850  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  #01  pc 0x00000000000e44e5  /apex/com.android.runtime/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+80)
  #02  pc 0x0000000000416db1  /apex/com.android.runtime/lib/libart.so (art::GoToRunnable(art::Thread*) (.llvm.14151189754156541143)+324)
  #03  pc 0x0000000000416c45  /apex/com.android.runtime/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:336)
  at android.os.Looper.loop (Looper.java:182)
  at android.app.ActivityThread.main (ActivityThread.java:7563)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:994)

**Comment by mry-ship** [comment]
![image](https://user-images.githubusercontent.com/19767759/215929797-7477323b-c1ef-4c43-9d86-53de9b7f858f.png)

**Comment by aurimasc** [comment]
Could you tell, which Unity version (exactly) you use?

**Comment by bw-atif** [comment]
We are having the same ANR with the latest unity mobile notifications v2.1.0 and unity v2021.3.16f1.

**Comment by cameronnotdoppler** [comment]
We have the same issue
Unity versions 2020.3.30f and 2021.3.16f
Plugin version 2.1.0

**Comment by KarahanOnarlar** [comment]
We also have the same problem. For us, 99% of ANRs happen on android 10 and in the background.
Unity version 2020.3.40f
Plugin versions 2.1.0 and 2.1.1
