### ISSUE TITLE
AndroidNotificationCenter.UserPermissionToPost does not consider the Status of the notifications  from the Android Settings

### ISSUE THREAD

**Issue by josefgrunig** [Unity-Technologies/com.unity.mobile.notifications#260]
From Android Settings app it's possible to disable Push Notification and 
`AndroidNotificationCenter.UserPermissionToPost`
does not reflect that setting. 

On Android <= 12 it returns always true, even if the user has disabled the setting, while it should return the value of
`NotificationManagerCompat.from(context).areNotificationsEnabled()`

**Comment by aurimasc** [comment]
API update to report this as well.
