### ISSUE TITLE
[iOS] unregisterForRemoteNotifications ?

### ISSUE THREAD

**Issue by alexandrefresnais** [Unity-Technologies/com.unity.mobile.notifications#277]
Hello guys,

Thanks for the great work, I managed to implement notifications in my iOS app quickly.

I am wondering why I see no possible call to `unregisterForRemoteNotifications` for push notifications ?

It seems to be the right way to unsubscribe from notifications when a user logs out.
For sure I can discard the token on my backend but calling `unregisterForRemoteNotifications` would enforce it locally even without internet connection.

Are you planning to add this method ?

Thank you in advance for reading me.

**Comment by aurimasc** [comment]
Implemented.
