### ISSUE TITLE
请教：如何走到UnityNotificationRestartOnBootReceiver类的onReceive方法

### ISSUE THREAD

**Issue by MrJLY** [Unity-Technologies/com.unity.mobile.notifications#284]
插件版本：MobileNotifications2.0.2
平台：Android
想问下什么情况下会走到UnityNotificationRestartOnBootReceiver类的onReceive方法，我已经开启了Reschedule Notifications on Device Restart选项，但是还是没有逻辑跑到这里

**Comment by aurimasc** [comment]
Only reports in English are accepted.
