### ISSUE TITLE
Consultation: How to go to the onReceive method of the UnityNotificationRestartOnBootReceiver class

### ISSUE THREAD

**Issue by MrJLY** [Unity-Technologies/com.unity.mobile.notifications#286]
Plugin version: MobileNotifications2.0.2

Platform: Android

I would like to ask under what circumstances I will go to the onReceive method of the UnityNotificationRestartOnBootReceiver class. I have already enabled the Reschedule Notifications on Device Restart option, but there is no logic to run here

**Comment by aurimasc** [comment]
It is called by the operating system after device restarts.
