### ISSUE TITLE
iOSNotificationCenter.GetLastRespondedNotification() does not work when cold start

### ISSUE THREAD

**Issue by kkfrank2** [Unity-Technologies/com.unity.mobile.notifications#316]
In iOS, after kill app, and click the notification to launch app,  iOSNotificationCenter.GetLastRespondedNotification() return null.
I test package 1.4.2 to 2.2.2, no one works

**Comment by kkfrank2** [comment]
> Are you checking for notification on the first frame? iOS does not deliver notifications right away, there is a couple frame delay.

Thanks for your reply. I sleep 1 second in awake event and not work .
I have no idea, and only have to dwongrade to 1.4.2, and follow this [fix](https://github.com/firebase/firebase-unity-sdk/issues/377#issuecomment-1165818349), 

Just add this code to fix this probelm. A little hack. 
> UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
> center.delegate = [UnityNotificationManager sharedInstance];

By the way, 1.4.2 have other problem(for example, cannot install in android 13 above, so I have to fix this too.. If I can use 2.2.2，that would be perfect)

**Comment by aurimasc** [comment]
> Thanks for your reply. I sleep 1 second in awake event and not work .

You mean Thread.Sleep()?
That doesn't solve the problem, it simply stalls the app, but the notification arrival happens on the same thread.
The proper way can be seen here: https://github.com/Unity-Technologies/com.unity.mobile.notifications/blob/3dc4c3aab454167d79a4b625a51c6a64294ca2a7/TestProjects/Main/Assets/Scripts/iOSTest.cs#L98

**Comment by SabeelMindstorm** [comment]
(Mobile notification package version 2.1.1 and unity version 2021.3.18f1). I followed the solution but still it returning null furthermore I checked https://assetstore.unity.com/packages/tools/integration/mobile-notifications-2-0-264705 this plugin as well to validate my implementation but still it give null.
Is there any permission need to set or should it work for some other unity version?
@aurimasc

**Comment by kkfrank2** [comment]
> com.unity.mobile.notifications/TestProjects/Main/Assets/Scripts/iOSTest.cs

Thank you. I used `yield return new WaitForSeconds(1f);` and not work. But I will use 2.2.2 to test again, to make sure if it's my problem.

**Comment by aurimasc** [comment]
Are you using any plugins that do something with notifications? Can you reproduce it in new project?

**Comment by kkfrank2** [comment]
> Are you using any plugins that do something with notifications? Can you reproduce it in new project?

Yes, I also used [firebase](https://firebase.google.com/docs/cloud-messaging/unity/client) push for android(At first, I used firebase for both android and ios. But in china, you cannot access google network, so in ios I switch to apns..). I will try to reproduce it in new project, it may take some times.

**Comment by kkfrank2** [comment]
I create a new project and it worked.  I will double check why my project not work..

**Comment by smarty-concrete** [comment]
There is a bug in the Firebase Messaging SDK that causes this issue to occur. I've submitted a pull request [here](https://github.com/firebase/firebase-cpp-sdk/pull/1604) in the firebase-cpp-sdk repo which will hopefully address this issue.
