### ISSUE TITLE
I need to schedule a notification after say 5 days and then repeat it daily

### ISSUE THREAD

**Issue by guohongyao** [Unity-Technologies/com.unity.mobile.notifications#325]
How can we schedule notifications and repeat them daily on IOS? I know there are Calendar Trigger and Time Trigger. But how to work out this feature? If you put hours and minutes on the calendar trigger then it will repeat the notification from the same day. Instead, I need to schedule a notification after say 5 days and then repeat it daily.

**Comment by aurimasc** [comment]
Please use Unity Discussions for support questions:
https://discussions.unity.com/
