### ISSUE TITLE
Broken DeviceToken for AuthorizationRequest, iOS 13

### ISSUE THREAD

**Issue by vlevitskiy-inceptionxr** [Unity-Technologies/com.unity.mobile.notifications#34]
it returns value something like
`deviceToken:  {length = 32, bytes = 0xe080fa88 e1e09edc 9d903e46 ad8f89e6 ... 06978693 2a1fefeb }`

**Comment by vincent-unity** [comment]
Thanks for reporting, will have a look.

**Comment by vincent-unity** [comment]
I looked into it today. I was testing on iOS 13.3.1, but I had the authorization request never been finished while testing. Will look into it further.

Btw: what's the iOS version you tested with?

**Comment by vlevitskiy-inceptionxr** [comment]
I was using iOS 13.4 on iPad 6th Gen

**Comment by vincent-unity** [comment]
Btw, could you please create a fogbugz case with repro project? Then our qa can verify it from our side.

**Comment by vincent-unity** [comment]
On which version of the package are you on? I tried with the latest 1.2.1-preview, the result looks right to me `0e1a568105d0b80aebb986ca4432d72a3af5f1aa8f849b5f0ac232cc12f1b9e8`.

**Comment by vincent-unity** [comment]
I tested on 1.1.0-preview, 1.2.1-preview, the device token looks right to me.
