### ISSUE TITLE
RenderTexture creation failed. 'Default' is not supported on this platform

### ISSUE THREAD

**Issue by p0w1nd** [Unity-Technologies/com.unity.mobile.notifications#39]
Hi,

I see this error while building on Android platform:

> RenderTexture creation failed. 'Default' is not supported on this platform. Use 'SystemInfo.SupportsRenderTextureFormat' C# API to check format support.
> UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
> UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
> UnityEngine.Logger:Log(LogType, Object, Object)
> UnityEngine.Debug:LogError(Object, Object)
> UnityEngine.Texture:ValidateFormat(RenderTextureFormat) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Texture.cs:347)
> UnityEngine.RenderTexture:.ctor(Int32, Int32, Int32, RenderTextureFormat, RenderTextureReadWrite) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Texture.cs:152)
> UnityEngine.RenderTexture:.ctor(Int32, Int32, Int32) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Texture.cs:170)
> Unity.Notifications.TextureAssetUtils:ScaleTexture(Texture2D, Int32, Int32) (at Library/PackageCache/com.unity.mobile.notifications@1.0.3/Editor/UnityNotificationEditorManager.cs:682)
> Unity.Notifications.UnityNotificationEditorManager:GenerateDrawableResourcesForExport() (at Library/PackageCache/com.unity.mobile.notifications@1.0.3/Editor/UnityNotificationEditorManager.cs:558)
> Unity.Notifications.AndroidNotificationResourcesPostProcessor:OnPostGenerateGradleAndroidProject(String) (at Library/PackageCache/com.unity.mobile.notifications@1.0.3/Editor/UnityNotificationEditorManager.cs:778)
> UnityEditor.Android.AndroidBuildPipelineInterfaces:OnGeneratePlatformProjectPostprocess(String, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Android/AndroidPostGenerateGradleProject.cs:39

)

After successfully build APK file, when testing notification on Android device I see that the icon is blank white, I guess it relates to this issue.

How can I fix it? Thanks.

Unity 2018.4.20f1
Mobile Notifications 1.0.3
 
MacBook Pro (Retina, 13-inch, Late 2013)
Processor 2.4 GHz Dual-Core Intel Core i5
Memory 8 GB 1600 MHz DDR3
Graphics Intel Iris 1536 MB

**Comment by vincent-unity** [comment]
Thanks for reporting. Could you please create a fogbugz case with repro project?

**Comment by p0w1nd** [comment]
Hi @vincent-unity 

I've just reported it via Unity Editor. Case number: 1238695

It happens 100% for me, even with a blank sample project:

- Create a blank sample 2D project
- Switch to Android platform, configure some basic stuff: Company Name, Package Name.
- Add Unity Mobile Notifications Package via Unity Package Manager
- Edit -> Project Settings -> Mobile Notifications Settings..
- Add Large Icon and Small Icon
- Quit Unity Editor
- Open the terminal, build APK with CLI, notice the "RenderTexture creation failed" message (at method ScaleTexture of Unity Mobile Notifications) while Unity does Post Processing to scale the sprite to different sizes for Android.

Thanks.

**Comment by newatlanta19006** [comment]
Happen to me as well. I cannot use Mobile Notifications with a batch mode (-nographics) build without seeing white squares

**Comment by vincent-unity** [comment]
Fixed at https://github.com/Unity-Technologies/com.unity.mobile.notifications/pull/54.
