### ISSUE TITLE
AuthorizationRequest never finishes when authorization is granted

### ISSUE THREAD

**Issue by NiceGuyAndersson** [Unity-Technologies/com.unity.mobile.notifications#42]
I'm having an issue getting 1.0.3 to work for iOS.
Running the following code 
```
        System.Collections.IEnumerator RequestAuthorization(System.Action callback)
        {
            using (var req = new AuthorizationRequest(AuthorizationOption.Alert | AuthorizationOption.Badge | AuthorizationOption.Sound, true))
            {
                while (!req.IsFinished)
                {
                    string res2 = "\n RequestAuthorization: \n";
                    res2 += "\n finished: " + req.IsFinished;
                    res2 += "\n granted :  " + req.Granted;
                    res2 += "\n error:  " + req.Error;
                    res2 += "\n deviceToken:  " + req.DeviceToken;
                    Debug.LogError(res2);
                    yield return null;
                };

                string res = "\n RequestAuthorization: \n";
                res += "\n finished: " + req.IsFinished;
                res += "\n granted :  " + req.Granted;
                res += "\n error:  " + req.Error;
                res += "\n deviceToken:  " + req.DeviceToken;
                Debug.LogError(res);

                callback?.Invoke();
            }
        }
```
Produces the following result:

1. First startup, prompts me to approve notifications which I do. 
`req.IsFinished` never becomes true and `req.Granted` is false. Error and DeviceToken is blank.

2. Second startup, no prompt since notifications have already been approved. 
`req.IsFinished` never becomes true and `req.Granted` is false. Error and DeviceToken is blank.

3. Disallow notifications in the devices settings for the app. No prompt. 
This time `req.IsFinished` becomes true and `req.Granted` is false. Error and DeviceToken is blank.

Is there a bug somewhere or am I missing some crucial step in setting up notifications for iOS?
Tried with both `Request Authorization on App Launch` on and off, and `Enable Push Notifications` on and off. We have previously used Push Notifications through another third-party API.

**Comment by NiceGuyAndersson** [comment]
I forgot to mention that the reason why I do AuthorizationRequest manually instead of using `Request Authorization on App Launch` is because when I did that Notifications could be scheduled without error but they would never trigger.

**Comment by vincent-unity** [comment]
Thanks for reporting. I assumed you're on iOS 13? Could you please open a fogbugz case with repro-project then we can have QA process it? Thanks.

**Comment by NiceGuyAndersson** [comment]
I can't seem to reproduce it with an otherwise empty project. I'll try to figure out if there's some conflict with other SDKs we're using.
It's iOS 13, yes. If I figure it out, what is fogbugz?

**Comment by vincent-unity** [comment]
Just sumbit a bug via unity bug reporter. :)

**Comment by vincent-unity** [comment]
I think the AuthorizationRequest won't finish if 
1. you don't have 'Enable Push Notifications' checked in the notification settings;
2. you're on iOS 13.

Could you try to confirm it?

**Comment by ChrysSilva** [comment]
Is this fixed? Im having the same behaviour in iOS 14: [https://github.com/Unity-Technologies/com.unity.mobile.notifications/issues/94](https://github.com/Unity-Technologies/com.unity.mobile.notifications/issues/94)
