### ISSUE TITLE
Can't set iOS Foreground Presentation Options to "Nothing" 

### ISSUE THREAD

**Issue by habitoti** [Unity-Technologies/com.unity.mobile.notifications#45]
Even with my Unity app in foreground, iOS notifications (sent from Firebase) were shown from the tray (in addition to my app handling them anyway). I found the global project setting "Remote Notification Foreground Presentation Options" that seem to do the trick of letting me choose how to handle the tray presentation. I would like to set it to "Nothing", but that doesn't work. It then instantly sets it back to "All". Currently I've set it to only "Sound", which at least just leaves me with the still annoying beep only. How can I suppress any notification handling outside of the running app?
I am using Mobile Notifications package 1.0.3.

**Comment by habitoti** [comment]
Still happening on 1.2.1-preview. I suppose "Nothing" should work, otherwise that option shouldn't be available at all.

**Comment by vincent-unity** [comment]
Could you please report a bug via Unity bug reporter? Thanks.

**Comment by vincent-unity** [comment]
Fixed at https://github.com/Unity-Technologies/com.unity.mobile.notifications/pull/56.
