### ISSUE TITLE
AndroidReceivedNotificationMainThreadDispatcher.cs allocation for each frame

### ISSUE THREAD

**Issue by teemukorh** [Unity-Technologies/com.unity.mobile.notifications#60]
Noticed when profiling our game that on AndroidReceivedNotificationMainThreadDispatcher.cs line 27 there is an allocation done each frame? Maybe re-use the same list to avoid GC.Alloc for each frame?

**Comment by pepoon** [comment]
Yea, could you use a class variable for that? Thanks.

**Comment by pepoon** [comment]
Is this thread dead?

**Comment by pepoon** [comment]
Thanks.
