### ISSUE TITLE
iOS Notification received callback

### ISSUE THREAD

**Issue by agrobost** [Unity-Technologies/com.unity.mobile.notifications#61]
UnityMobileNotification 1.3.0
Unity: 2019.2.17f1
Platerform: iOS

Hi, the callback iOSNotificationCenter.OnNotificationReceived doesn't work, in foreground or background.
Do you have an idea ?

Best regards

**Comment by aurimasc** [comment]
Using latest version of the package the sample project does work for me and I see from the log that callback gets called.
