### ISSUE TITLE
[Feature] Please add a way to open the OS Notification Settings.

### ISSUE THREAD

**Issue by legionaryu** [Unity-Technologies/com.unity.mobile.notifications#62]
Hi folks,

I'm using your package in my game and I can't find a way to prompt the Notification Settings ( on Android open the Notification Settings Activity, and on iOS the URL that I will open with Application.OpenURL).
In my case, the user can check if the notification is enabled on the Settings menu and click on the button to enable it, but the only way to do it, so far, is creating a custom Unity Plug-in, so all I'm asking is to add support for opening the native Notification Settings in your package.

Cheers

**Comment by aurimasc** [comment]
Created ticket for this feature in JIRA.
