### ISSUE TITLE
[Android] How can i get delivered push notification after launch by app, not the push notification.  

### ISSUE THREAD

**Issue by Ultraa** [Unity-Technologies/com.unity.mobile.notifications#77]
Good day everyone!

[Android] How can i get delivered push notification after the launch app, not after click on the push notification.  
In iOS I can get it like that:

`Good day everyone!

[Android] How can i get delivered push notification after the launch app, not after click on the push notification.  
In iOS I can get it like that:

    **private void IOSGetLastRespondedNotification()
    {
        iOSNotification notification = null;

        if (iOSNotificationCenter.GetLastRespondedNotification() != null)
        {
            notification = iOSNotificationCenter.GetLastRespondedNotification();
        } 
        else if (iOSNotificationCenter.GetDeliveredNotifications() != null &&
                 iOSNotificationCenter.GetDeliveredNotifications().Length > 0)
        {
            notification = iOSNotificationCenter.GetDeliveredNotifications().Last();
        }

        if (notification != null)
        {
            HandleIOSRespondedNotification(notification);
        }
    }**

But in Android I can use only this:
`var notificationIntentData = AndroidNotificationCenter.GetLastNotificationIntent();`

The scenario:
1. Send push.
2. Receive push.
3. Open app by icon.
4. Android say no anything, but iOS get last push notification and handled it.

**Comment by aurimasc** [comment]
This can only be achieved via notification receiver. You have to either write your own receiver or modify the one in the package.
