### ISSUE TITLE
Delayed Application Launch When Package Present - iOS

### ISSUE THREAD

**Issue by codyward-skybox** [Unity-Technologies/com.unity.mobile.notifications#89]
We have an external package which is timing sensitive. It appears when the Mobile Notifications package is present in our iOS builds, we are hitting a race condition due to the presence of the Mobile Notifications package.

**Comment by aurimasc** [comment]
Can you submit a bug through Unity with the project containing other package showcasing a bug? Cause this report is not helpful.
