### ISSUE TITLE
Custom layout for Android?

### ISSUE THREAD

**Issue by NarekSaghiyan** [Unity-Technologies/com.unity.mobile.notifications#90]
A lot of games on Android have great notifications with custom layout. I would like to add that to my notifications as well, but as far as I am concerned there is no option for that, I saw that custom sounds was planned to be done for Mobile Notifications Plugin (there was a TO DO comment in source code), but 2 years later it was never added.

**Comment by abogarsukov-braingames** [comment]
I'm interested in this feature as well. We have to change the plugin code to support rich notifications. It would be good to have it out-of-the box.

**Comment by vaidasma** [comment]
Added a feature request for the developer to process. Thank you guys for pointing this out!
