### ISSUE TITLE
[Feature Request][Android] Handle setShowWhen and setWhen 

### ISSUE THREAD

**Issue by wise89** [Unity-Technologies/com.unity.mobile.notifications#93]
Nice to have:
Handle android native method setShowWhen or/and setWhen.
https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setShowWhen(boolean)

Or alternative exposes native android Builder.

**Comment by aurimasc** [comment]
You can set these by setting ShowTimestamp and CustomTimestamp.
