### ISSUE TITLE
AuthorizationRequest never completes on iOS 14 on package version 1.3.2

### ISSUE THREAD

**Issue by ChrysSilva** [Unity-Technologies/com.unity.mobile.notifications#94]
Hi, Im just implementing this package (migrating from using UnityEngine.iOS.NotificationServices.deviceToken) on a live game, notifications permissions are added at certain point in the game, and players might already accepted in a previous version.

We have other plugins and one of them handles the System permission request.

We have the iOS settings:

- Enable Push Notifications = TRUE
- Register for Push Notifications on App Launch = FALSE.
- Enable Release Environment for APS = TRUE
- Include CodeLocation Framework = TRUE

The code used at the start of the game is:

```
private void InitializeiOSPushTokenIfAutorized()
{
    var iOSNotificationSettings = iOSNotificationCenter.GetNotificationSettings();
    _iLog.Info(()=> $"SDKManager iOS PushNotificationsSettings with status:{iOSNotificationSettings.AuthorizationStatus} Setting:{iOSNotificationSettings.AlertSetting} and Style:{iOSNotificationSettings.AlertStyle}");
    if (iOSNotificationSettings.AuthorizationStatus == AuthorizationStatus.Authorized)
    {
        StartCoroutine(RequestIOSPushNotificationToken());
    }
}
    
```
    private IEnumerator RequestIOSPushNotificationToken()
    {
        _iLog.Info(()=> $"SDKManager requesting iOS PushNotificationsAuthorization");
        using (var req = new AuthorizationRequest(AuthorizationOption.Alert | AuthorizationOption.Badge, true))
        {
            while (!req.IsFinished)
            {
                yield return 0;
            }

            string formattedPushToken = req.DeviceToken.Replace("-", "");
            
            string result = "\n RequestAuthorization: \n";
            result += "\n finished: " + req.IsFinished;
            result += "\n granted :  " + req.Granted;
            result += "\n error:  " + req.Error;
            result += "\n deviceToken:  " + req.DeviceToken;
            result += "\n FormattedDeviceToken:  " + formattedPushToken;
            
            _iLog.Info(() => result);

            if (req.Granted && !string.IsNullOrEmpty(formattedPushToken))
            {
                OnPushTokenReceived(formattedPushToken);
            }
        }
    }

I can see the log for "SDKManager requesting iOS PushNotificationsAuthorization" but never the next one (RequestAuthorization), this player has Authorized the notifications already.

**Comment by ChrysSilva** [comment]
Could it be that :

````
public AuthorizationRequest(AuthorizationOption authorizationOption, bool registerForRemoteNotifications)
{
    iOSNotificationsWrapper.RegisterAuthorizationRequestCallback();
    iOSNotificationsWrapper.RequestAuthorization((int)authorizationOption, registerForRemoteNotifications);
    iOSNotificationCenter.OnAuthorizationRequestCompleted += OnAuthorizationRequestCompleted;
}
````
needs to be :
```
public AuthorizationRequest(AuthorizationOption authorizationOption, bool registerForRemoteNotifications)
{
    iOSNotificationsWrapper.RegisterAuthorizationRequestCallback();
    iOSNotificationCenter.OnAuthorizationRequestCompleted += OnAuthorizationRequestCompleted;
    iOSNotificationsWrapper.RequestAuthorization((int)authorizationOption, registerForRemoteNotifications);
}
```
in case the request returns immediately upon calling "iOSNotificationsWrapper.RequestAuthorization"?

**Comment by ChrysSilva** [comment]
tried also 1.4.0 with the same result =/

**Comment by aurimasc** [comment]
I've tried this using a test project from package, so the case is:
- when you pass true for second argument to AuthorizationRequest, the request will complete only after push notifications are granted
- request for push notifications require network; if you run request on device without network, the request will not complete until network becomes available.

So, if you need authorization for local notifications, but not push, pass false as second argument. If you need both, probably best to do two requests.

**Comment by ChrysSilva** [comment]
so in my case passing true when they have already granted permission for push notifications never ends thats the problem.

**Comment by vaidasma** [comment]
Hey, could you submit a bug report via Unity's bug reporter (Help > Submit a Bug)? Please include essential information so it would be easier for us to understand your issue:

• Project that reproduces the issue
• Android / iOS issue
• Notification Package version, that you are using
• Unity editor's version, that you are using
• Mobile devices and their OS, that reproduce the issue
