### ISSUE TITLE
Implicit PendingIntent Vulnerability

### ISSUE THREAD

**Issue by AntonPetrov83** [Unity-Technologies/com.unity.mobile.notifications#99]
Hi,

Looks like after we have integrated Mobile Notifications 1.3.2 we received an e-mail from the Google:

> Your app(s) contain an Implicit PendingIntent issue.
> To address this issue, follow the steps in this [Google Help Center](https://notifications.google.com/g/p/AD-FnEyMqkufpTSko58ywH25jwojLR4HL9ZsYGoo48dnW3pFPbPFb-C6lsQQB2QCyYKRtBJHLKhTWxbMXcvpigRxYD_86lPSB2-zraPS2UAbTC27Eb0) article.

I see that you do not use `FLAG_IMMUTABLE` in the package. Can it be the problem?

Thank you.

**Comment by chinpok** [comment]
Have a same issue but disabling mobile notification do not fix issue

**Comment by chinpok** [comment]
https://forum.unity.com/threads/vulnerability-implicit-pendingintent.1131070/

**Comment by AntonPetrov83** [comment]
Yeah, its devtodev sdk. They released an update.

**Comment by aurimasc** [comment]
The fix for this has landed to master.

**Comment by yantian001** [comment]
This issue still happened on Mobile Notifications 2.0.0 with Unity 2019.4.38f1c1
![image](https://user-images.githubusercontent.com/8159444/164884523-03435bd1-21f6-4f9c-9cde-b2262bc822b1.png)
